//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/SPlayerController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SPlayerController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SPlayerController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SPlayerController"",
    ""maps"": [
        {
            ""name"": ""SGamePlay"",
            ""id"": ""c91cc503-c0bf-494f-be62-4a88be32730d"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8bbf8308-1d06-45f8-be5c-25c0a9962585"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cursor"",
                    ""type"": ""PassThrough"",
                    ""id"": ""76090a08-d9d5-4e29-908f-636ee8818f66"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""jump"",
                    ""type"": ""Button"",
                    ""id"": ""64298a58-6eb3-4194-b675-2c7ce2c32967"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c6c29f2e-5a3d-4b26-8c1b-523fe01a4c49"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e034d292-7c94-4392-92ef-15e794143ace"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9d00b54-4efa-4b93-acb4-2865e2d4b236"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button3"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SGamePlay
        m_SGamePlay = asset.FindActionMap("SGamePlay", throwIfNotFound: true);
        m_SGamePlay_Move = m_SGamePlay.FindAction("Move", throwIfNotFound: true);
        m_SGamePlay_Cursor = m_SGamePlay.FindAction("Cursor", throwIfNotFound: true);
        m_SGamePlay_jump = m_SGamePlay.FindAction("jump", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SGamePlay
    private readonly InputActionMap m_SGamePlay;
    private ISGamePlayActions m_SGamePlayActionsCallbackInterface;
    private readonly InputAction m_SGamePlay_Move;
    private readonly InputAction m_SGamePlay_Cursor;
    private readonly InputAction m_SGamePlay_jump;
    public struct SGamePlayActions
    {
        private @SPlayerController m_Wrapper;
        public SGamePlayActions(@SPlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_SGamePlay_Move;
        public InputAction @Cursor => m_Wrapper.m_SGamePlay_Cursor;
        public InputAction @jump => m_Wrapper.m_SGamePlay_jump;
        public InputActionMap Get() { return m_Wrapper.m_SGamePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SGamePlayActions set) { return set.Get(); }
        public void SetCallbacks(ISGamePlayActions instance)
        {
            if (m_Wrapper.m_SGamePlayActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_SGamePlayActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_SGamePlayActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_SGamePlayActionsCallbackInterface.OnMove;
                @Cursor.started -= m_Wrapper.m_SGamePlayActionsCallbackInterface.OnCursor;
                @Cursor.performed -= m_Wrapper.m_SGamePlayActionsCallbackInterface.OnCursor;
                @Cursor.canceled -= m_Wrapper.m_SGamePlayActionsCallbackInterface.OnCursor;
                @jump.started -= m_Wrapper.m_SGamePlayActionsCallbackInterface.OnJump;
                @jump.performed -= m_Wrapper.m_SGamePlayActionsCallbackInterface.OnJump;
                @jump.canceled -= m_Wrapper.m_SGamePlayActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_SGamePlayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Cursor.started += instance.OnCursor;
                @Cursor.performed += instance.OnCursor;
                @Cursor.canceled += instance.OnCursor;
                @jump.started += instance.OnJump;
                @jump.performed += instance.OnJump;
                @jump.canceled += instance.OnJump;
            }
        }
    }
    public SGamePlayActions @SGamePlay => new SGamePlayActions(this);
    public interface ISGamePlayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnCursor(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
    }
}
